spring.application.name=airline-api-gateway
server.port=5001

# 1. Yönlendirme Ayarı (Backend 5000'e gönderir)
spring.cloud.gateway.routes[0].id=flight-service
spring.cloud.gateway.routes[0].uri=http://localhost:5000
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/flights/**

# 2. CORS Ayarı (Frontend 5173'e izin verir) - KRİTİK KISIM
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*