spring.application.name=airline-api-gateway
server.port=5001

spring.cloud.gateway.server.webflux.routes[0].id=flight-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://airline-backend-env-1.eba-gdrgmvqz.eu-north-1.elasticbeanstalk.com
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/**

management.endpoints.web.exposure.include=health,info